### ISSUE TITLE
Error when using min() and max() to find bin edges

### ISSUE THREAD

**Issue by KarthikGanesan88** [francois-rozet/torchist#4] opened 2023-11-28 22:06 UTC
### Description

Runtime error when calculating bin edges using .min() and .max() functions, instead of specifying fixed numerical values. 

`RuntimeError: shape '[10]' is invalid for input of size 11`

Using `np.histogram` works correctly. 

### Reproduce

A minimal working example demonstrating the current behavior.

```python
import torch
import torchist
import numpy as np

x = np.random.rand(10000)
x_min, x_max = x.min(), x.max()

edges = np.linspace(x_min, x_max, 11)
hist_np, _ = np.histogram(x, bins=edges)
print(hist_np.shape)

x_t = torch.from_numpy(x).cuda()
edges_t = torch.from_numpy(edges).cuda()
hist_t = torchist.histogram(x_t, edges=edges_t) # Error is reported here. 
print(hist_t.shape)  
```

### Expected behavior

Both `torchist` and `numpy` results should work and produce matching results. 

### Causes and solution

Slightly changing the values of `x_min` and `x_max` solves the issue. 
` x_min, x_max = x.min()*1.01 , x.max()*1.01` 

### Environment

* torchist version: 0.2.1
* PyTorch version: 1.12.1
* Python version: 3.10
* OS: Ubuntu 20.04 LTS

**Comment by francois-rozet** [comment] 2023-11-29 15:01
Hello @KarthikGanesan88, thank you for the bug report!

I can reproduce the error. It is due to the index of `x = edges[-1]` being `bins` instead of `bins - 1` after `torch.searchsorted` or `torch.bucketize`. I will fix this soon.

> Edit: It's actually an error that was reported by #1 and #2, but your minimal working example allowed me to reproduce and understand the bug. Thank you very much !!!

**Comment by francois-rozet** [comment] 2023-11-29 15:25
The issue should be fixed in the latest PyPi release. Thank you again!

**Closed as completed by francois-rozet** 2023-11-29 15:25 UTC
Labels: bug

**Comment by KarthikGanesan88** [comment] 2023-11-29 16:58
Hi @francois-rozet, many thanks for your prompt help with this! I also wanted to thank you for making this package and releasing it.

**Comment by francois-rozet** [comment] 2023-11-29 17:00
You're welcome @KarthikGanesan88! Can you confirm that the new release fixes your issue?
